package com.example.datacave_beta.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Quest {
    private Long id;
    private String title;
    private String description;
    private String category;
    private String categoryIcon;
    private double reward;
    private String difficulty;
    private String deadline;
    private int requiredCount;
    private int completedCount;
    private String company;
    private List<String> tags;
    private String status;
    private int estimatedMinutes;

    // --- demand-side extensions ---------------------------------------------
    private String requiredTier;  // null = open to all; e.g. "Silver Mapper", "Verified Expert"
    private boolean expertOnly;   // requires a verified domain expert
    private String domain;        // expert domain, e.g. "surgical", "fashion", "marketing"
    private Long schemaId;        // attached annotation schema (N)
    private Long standingQuestId; // set if generated by a standing quest / subscription (E)
}
